SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [stage].[Map_Customers]

AS

TRUNCATE TABLE stage.Customers

INSERT INTO stage.Customers (
 [CustomerID]				
,[cus_no]					
,[cus_name]				
,[addr_1]					
,[addr_2]					
,[addr_3]					
,[city]					
,[state]					
,[zip]					
,[country]				
,[start_dt]				
,[slspsn_no]				
,[fullname]				
,[cus_type_cd]			
,[cus_type_desc]			
,[par_cus_no]				
,[Parent_Customer_Name]	
,[ar_terms_cd]			
,[Terms_cd_Desc]			
,[dsc_pct]				
,[user_def_fld_1]			
,[user_def_fld_2]			
,[user_def_fld_3]			
,[user_def_fld_4]			
,[user_def_fld_5]			
,[cus_note_1]				
,[cus_note_2]				
,[cus_note_3]				
,[cus_note_4]				
,[cus_note_5]				
,[terr]					
,[Company]					
)

SELECT [CustomerID]					
	  ,[cus_no]						
      ,[cus_name]					
      ,[addr_1]						
      ,[addr_2]						
      ,[addr_3]						
      ,[city]						
      ,[state]						
      ,[zip]						
      ,[country]					
      ,[start_dt]					
      ,[slspsn_no]					
      ,[fullname]					
      ,[cus_type_cd]				
      ,[cus_type_desc]				
      ,[par_cus_no]					
      ,[Parent_Customer_Name]		
      ,[ar_terms_cd]				
      ,[Terms_cd_Desc]				
      ,[dsc_pct]					
      ,[user_def_fld_1]				
      ,[user_def_fld_2]				
      ,[user_def_fld_3]				
      ,[user_def_fld_4]				
      ,[user_def_fld_5]				
      ,[cus_note_1]					
      ,[cus_note_2]					
      ,[cus_note_3]					
      ,[cus_note_4]					
      ,[cus_note_5]					
      ,[terr]						
	  ,[Company]						
FROM [store].[ClarityRx_Customers]



INSERT INTO stage.Customers (
 [CustomerID]				
,[cus_no]					
,[cus_name]				
,[addr_1]					
,[addr_2]					
,[addr_3]					
,[city]					
,[state]					
,[zip]					
,[country]				
,[start_dt]				
,[slspsn_no]				
,[fullname]				
,[cus_type_cd]			
,[cus_type_desc]			
,[par_cus_no]				
,[Parent_Customer_Name]	
,[ar_terms_cd]			
,[Terms_cd_Desc]			
,[dsc_pct]				
,[user_def_fld_1]			
,[user_def_fld_2]			
,[user_def_fld_3]			
,[user_def_fld_4]			
,[user_def_fld_5]			
,[cus_note_1]				
,[cus_note_2]				
,[cus_note_3]				
,[cus_note_4]				
,[cus_note_5]				
,[terr]					
,[Company]					
)

SELECT [CustomerID]					
	  ,[cus_no]						
      ,[cus_name]					
      ,[addr_1]						
      ,[addr_2]						
      ,[addr_3]						
      ,[city]						
      ,[state]						
      ,[zip]						
      ,[country]					
      ,[start_dt]					
      ,[slspsn_no]					
      ,[fullname]					
      ,[cus_type_cd]				
      ,[cus_type_desc]				
      ,[par_cus_no]					
      ,[Parent_Customer_Name]		
      ,[ar_terms_cd]				
      ,[Terms_cd_Desc]				
      ,[dsc_pct]					
      ,[user_def_fld_1]				
      ,[user_def_fld_2]				
      ,[user_def_fld_3]				
      ,[user_def_fld_4]				
      ,[user_def_fld_5]				
      ,[cus_note_1]					
      ,[cus_note_2]					
      ,[cus_note_3]					
      ,[cus_note_4]					
      ,[cus_note_5]					
      ,[terr]						
	  ,[Company]						
FROM [store].[DermaE_Customers]


INSERT INTO stage.Customers (
 [CustomerID]				
,[cus_no]					
,[cus_name]				
,[addr_1]					
,[addr_2]					
,[addr_3]					
,[city]					
,[state]					
,[zip]					
,[country]				
,[start_dt]				
,[slspsn_no]				
,[fullname]				
,[cus_type_cd]			
,[cus_type_desc]			
,[par_cus_no]				
,[Parent_Customer_Name]	
,[ar_terms_cd]			
,[Terms_cd_Desc]			
,[dsc_pct]				
,[user_def_fld_1]			
,[user_def_fld_2]			
,[user_def_fld_3]			
,[user_def_fld_4]			
,[user_def_fld_5]			
,[cus_note_1]				
,[cus_note_2]				
,[cus_note_3]				
,[cus_note_4]				
,[cus_note_5]				
,[terr]					
,[Company]					
)

SELECT [CustomerID]					
	  ,[cus_no]						
      ,[cus_name]					
      ,[addr_1]						
      ,[addr_2]						
      ,[addr_3]						
      ,[city]						
      ,[state]						
      ,[zip]						
      ,[country]					
      ,[start_dt]					
      ,[slspsn_no]					
      ,[fullname]					
      ,[cus_type_cd]				
      ,[cus_type_desc]				
      ,[par_cus_no]					
      ,[Parent_Customer_Name]		
      ,[ar_terms_cd]				
      ,[Terms_cd_Desc]				
      ,[dsc_pct]					
      ,[user_def_fld_1]				
      ,[user_def_fld_2]				
      ,[user_def_fld_3]				
      ,[user_def_fld_4]				
      ,[user_def_fld_5]				
      ,[cus_note_1]					
      ,[cus_note_2]					
      ,[cus_note_3]					
      ,[cus_note_4]					
      ,[cus_note_5]					
      ,[terr]						
	  ,[Company]						
FROM [store].[Think_Customers]


INSERT INTO stage.Customers (
 [CustomerID]				
,[cus_no]					
,[cus_name]				
,[addr_1]					
,[addr_2]					
,[addr_3]					
,[city]					
,[state]					
,[zip]					
,[country]				
,[start_dt]				
,[slspsn_no]				
,[fullname]				
,[cus_type_cd]			
,[cus_type_desc]			
,[par_cus_no]				
,[Parent_Customer_Name]	
,[ar_terms_cd]			
,[Terms_cd_Desc]			
,[dsc_pct]				
,[user_def_fld_1]			
,[user_def_fld_2]			
,[user_def_fld_3]			
,[user_def_fld_4]			
,[user_def_fld_5]			
,[cus_note_1]				
,[cus_note_2]				
,[cus_note_3]				
,[cus_note_4]				
,[cus_note_5]				
,[terr]					
,[Company]					
)

SELECT [CustomerID]					
	  ,[cus_no]						
      ,[cus_name]					
      ,[addr_1]						
      ,[addr_2]						
      ,[addr_3]						
      ,[city]						
      ,[state]						
      ,[zip]						
      ,[country]					
      ,[start_dt]					
      ,[slspsn_no]					
      ,[fullname]					
      ,[cus_type_cd]				
      ,[cus_type_desc]				
      ,[par_cus_no]					
      ,[Parent_Customer_Name]		
      ,[ar_terms_cd]				
      ,[Terms_cd_Desc]				
      ,[dsc_pct]					
      ,[user_def_fld_1]				
      ,[user_def_fld_2]				
      ,[user_def_fld_3]				
      ,[user_def_fld_4]				
      ,[user_def_fld_5]				
      ,[cus_note_1]					
      ,[cus_note_2]					
      ,[cus_note_3]					
      ,[cus_note_4]					
      ,[cus_note_5]					
      ,[terr]						
	  ,[Company]						
FROM [store].[Topiderm_Customers]


INSERT INTO stage.Customers (
 [CustomerID]				
,[cus_no]					
,[cus_name]				
,[addr_1]					
,[addr_2]					
,[addr_3]					
,[city]					
,[state]					
,[zip]					
,[country]				
,[start_dt]				
,[slspsn_no]				
,[fullname]				
,[cus_type_cd]			
,[cus_type_desc]			
,[par_cus_no]				
,[Parent_Customer_Name]	
,[ar_terms_cd]			
,[Terms_cd_Desc]			
,[dsc_pct]				
,[user_def_fld_1]			
,[user_def_fld_2]			
,[user_def_fld_3]			
,[user_def_fld_4]			
,[user_def_fld_5]			
,[cus_note_1]				
,[cus_note_2]				
,[cus_note_3]				
,[cus_note_4]				
,[cus_note_5]				
,[terr]					
,[Company]					
)

SELECT [CustomerID]					
	  ,[cus_no]						
      ,[cus_name]					
      ,[addr_1]						
      ,[addr_2]						
      ,[addr_3]						
      ,[city]						
      ,[state]						
      ,[zip]						
      ,[country]					
      ,[start_dt]					
      ,[slspsn_no]					
      ,[fullname]					
      ,[cus_type_cd]				
      ,[cus_type_desc]				
      ,[par_cus_no]					
      ,[Parent_Customer_Name]		
      ,[ar_terms_cd]				
      ,[Terms_cd_Desc]				
      ,[dsc_pct]					
      ,[user_def_fld_1]				
      ,[user_def_fld_2]				
      ,[user_def_fld_3]				
      ,[user_def_fld_4]				
      ,[user_def_fld_5]				
      ,[cus_note_1]					
      ,[cus_note_2]					
      ,[cus_note_3]					
      ,[cus_note_4]					
      ,[cus_note_5]					
      ,[terr]						
	  ,[Company]						
FROM [store].[Topix_Customers]

update c
SET IntracompanyFlag = CASE WHEN CustomerID in
									(
									  'Topiderm_100107'
									, 'Topiderm_109242'
									, 'Topiderm_109332'
									, 'DermaE_110663'
									, 'Topiderm_109489'
									, 'Topix_106062'
									, 'Topix_122543'
									, 'Topix_118646'
									, 'Topix_114852'
									, 'Topix_116631'
									, 'ClarityRx_4945'
									, 'Topix_106063'
									, 'ClarityRx_4788'
									, 'Topix_111961'
									, 'ClarityRx_1025'
									)
							THEN 'Yes'
							ELSE 'No'
							END

from stage.Customers c
GO