SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [stage].[Map_Items]

AS

TRUNCATE TABLE stage.Items

INSERT INTO stage.Items (
	   [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]
)

SELECT [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]				
FROM [store].[ClarityRx_Items]



INSERT INTO stage.Items (
	   [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]
)

SELECT [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]				
FROM [store].[DermaE_Items]


INSERT INTO stage.Items (
	   [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]
)

SELECT [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]				
FROM [store].[Think_Items]



INSERT INTO stage.Items (
	   [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]
)

SELECT [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]				
FROM [store].[Topiderm_Items]




INSERT INTO stage.Items (
	   [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]
)

SELECT [ItemID]
      ,[item_no]
      ,[item_desc_1]
      ,[item_desc_2]
      ,[prod_cat]
      ,[prod_cat_desc]
      ,[mat_cost_type]
      ,[mat_cost_desc]
      ,[loc]
      ,[uom]
      ,[activity_cd]
      ,[activity_dt]
      ,[item_note_1]
      ,[item_note_2]
      ,[item_note_3]
      ,[item_note_4]
      ,[item_note_5]
      ,[user_def_fld_1]
      ,[user_def_fld_2]
      ,[user_def_fld_3]
      ,[user_def_fld_4]
      ,[user_def_fld_5]
      ,[price]
      ,[avg_cost]
      ,[last_cost]
      ,[Company]				
FROM [store].[Topix_Items]
GO