CREATE TABLE [raw].[XXX_Topiderm_Customers] (
  [cus_no] [nvarchar](255) NULL,
  [cus_name] [nvarchar](255) NULL,
  [addr_1] [nvarchar](255) NULL,
  [addr_2] [nvarchar](255) NULL,
  [addr_3] [nvarchar](255) NULL,
  [city] [nvarchar](255) NULL,
  [state] [nvarchar](255) NULL,
  [zip] [nvarchar](255) NULL,
  [country] [nvarchar](255) NULL,
  [start_dt] [nvarchar](255) NULL,
  [slspsn_no] [nvarchar](255) NULL,
  [fullname] [nvarchar](255) NULL,
  [cus_type_cd] [nvarchar](255) NULL,
  [cus_type_desc] [nvarchar](255) NULL,
  [par_cus_no] [nvarchar](255) NULL,
  [Parent_Customer_Name] [nvarchar](255) NULL,
  [ar_terms_cd] [nvarchar](255) NULL,
  [Terms_cd_Desc] [nvarchar](255) NULL,
  [dsc_pct] [nvarchar](255) NULL,
  [user_def_fld_1] [nvarchar](255) NULL,
  [user_def_fld_2] [nvarchar](255) NULL,
  [user_def_fld_3] [nvarchar](255) NULL,
  [user_def_fld_4] [nvarchar](255) NULL,
  [user_def_fld_5] [nvarchar](255) NULL,
  [cus_note_1] [nvarchar](255) NULL,
  [cus_note_2] [nvarchar](255) NULL,
  [cus_note_3] [nvarchar](255) NULL,
  [cus_note_4] [nvarchar](255) NULL,
  [cus_note_5] [nvarchar](255) NULL,
  [terr] [nvarchar](255) NULL
)
ON [PRIMARY]
GO