CREATE TABLE [raw].[Think_Customers] (
  [cus_no] [varchar](255) NULL,
  [cus_name] [varchar](255) NULL,
  [addr_1] [varchar](255) NULL,
  [addr_2] [varchar](255) NULL,
  [addr_3] [varchar](255) NULL,
  [city] [varchar](255) NULL,
  [state] [varchar](255) NULL,
  [zip] [varchar](255) NULL,
  [country] [varchar](255) NULL,
  [start_dt] [varchar](255) NULL,
  [slspsn_no] [varchar](255) NULL,
  [fullname] [varchar](255) NULL,
  [cus_type_cd] [varchar](255) NULL,
  [cus_type_desc] [varchar](255) NULL,
  [par_cus_no] [varchar](255) NULL,
  [Parent_Customer_Name] [varchar](255) NULL,
  [ar_terms_cd] [varchar](255) NULL,
  [Terms_cd_Desc] [varchar](255) NULL,
  [dsc_pct] [varchar](255) NULL,
  [user_def_fld_1] [varchar](255) NULL,
  [user_def_fld_2] [varchar](255) NULL,
  [user_def_fld_3] [varchar](255) NULL,
  [user_def_fld_4] [varchar](255) NULL,
  [user_def_fld_5] [varchar](255) NULL,
  [cus_note_1] [varchar](255) NULL,
  [cus_note_2] [varchar](255) NULL,
  [cus_note_3] [varchar](255) NULL,
  [cus_note_4] [varchar](255) NULL,
  [cus_note_5] [varchar](255) NULL,
  [terr] [varchar](255) NULL
)
ON [PRIMARY]
GO