CREATE TABLE [store].[Think_Invoices] (
  [InvoiceID] [varchar](531) NOT NULL,
  [CustomerID] [varchar](100) NOT NULL,
  [ItemID] [varchar](100) NOT NULL,
  [orig_ord_type] [varchar](100) NULL,
  [ord_type] [varchar](100) NULL,
  [ord_no] [varchar](100) NULL,
  [entered_dt] [date] NULL,
  [ord_dt] [date] NULL,
  [oe_po_no] [varchar](100) NULL,
  [cus_no] [varchar](100) NULL,
  [bill_to_name] [varchar](100) NULL,
  [cus_alt_adr_cd] [varchar](100) NULL,
  [ship_to_name] [varchar](100) NULL,
  [ship_via_cd] [varchar](100) NULL,
  [ar_terms_cd] [varchar](100) NULL,
  [ship_instruction_1] [varchar](100) NULL,
  [ship_instruction_2] [varchar](100) NULL,
  [slspsn_no] [varchar](100) NULL,
  [tot_sls_amt] [money] NULL,
  [tot_sls_disc] [money] NULL,
  [tot_tax_amt] [money] NULL,
  [tot_cost] [money] NULL,
  [misc_amt] [money] NULL,
  [frt_amt] [money] NULL,
  [sls_tax_amt_1] [money] NULL,
  [sls_tax_amt_2] [money] NULL,
  [sls_tax_amt_3] [money] NULL,
  [inv_no] [varchar](100) NULL,
  [inv_dt] [date] NULL,
  [tot_dollars] [money] NULL,
  [bill_to_no] [varchar](100) NULL,
  [ship_to_city] [varchar](100) NULL,
  [ship_to_state] [varchar](100) NULL,
  [ship_to_zip] [varchar](100) NULL,
  [bill_to_city] [varchar](100) NULL,
  [bill_to_state] [varchar](100) NULL,
  [bill_to_zip] [varchar](100) NULL,
  [line_seq_no] [varchar](100) NULL,
  [item_no] [varchar](100) NULL,
  [loc] [varchar](100) NULL,
  [item_desc_1] [varchar](100) NULL,
  [item_desc_2] [varchar](100) NULL,
  [qty_ordered] [decimal](18, 9) NULL,
  [qty_to_ship] [decimal](18, 9) NULL,
  [unit_price] [money] NULL,
  [discount_pct] [decimal](18, 9) NULL,
  [request_dt] [date] NULL,
  [qty_bkord] [decimal](18, 9) NULL,
  [qty_return_to_stk] [decimal](18, 9) NULL,
  [unit_cost] [money] NULL,
  [prod_cat] [varchar](100) NULL,
  [user_def_fld_1] [varchar](100) NULL,
  [user_def_fld_2] [varchar](100) NULL,
  [user_def_fld_3] [varchar](100) NULL,
  [user_def_fld_4] [varchar](100) NULL,
  [user_def_fld_5] [varchar](100) NULL,
  [sls_amt] [money] NULL,
  [cost_amt] [money] NULL,
  [Company] [varchar](100) NULL,
  CONSTRAINT [PK_StoreThink_Invoices] PRIMARY KEY CLUSTERED ([InvoiceID])
)
ON [PRIMARY]
GO